# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://andreahaas.com'
baseurl: ''
lang: en-GB
title: 'Andrea Haas | Holistic sex therapist'
description: 'Andrea Haas, Holistic Sex Therapist in Sydney, specialises in sexual dysfunction, premature ejaculation, painful sex, sexual desire and libido.'
permalink: pretty
logo: '/assets/logos/logo.svg'
email: andrea@andreahaas.com
phone: 0425 218 022
google_analytics: 'UA-7523913-1'
google_analytics_anonymize_ip: false

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Services
  url: /services/
- title: About
  url: /about/
- title: Contact
  url: /contact/
# - title: Blog
#   url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
